# Generated by Django 3.2.12 on 2023-10-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shirts',
            new_name='Shirt',
        ),
    ]
