# Generated by Django 3.2.12 on 2023-10-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_shirt_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='brand',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
